config/routes.rb
Rails.application.routes.draw do

  root 'sales#index'
  get 'login' => 'sessions#new', :as => 'login'
  post 'login' => 'sessions#create', :as => 'login_submit'

  resources :timeline
  resources :users

  resources :properties do
     resources :tickets
     resources :memberships
  end

end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :property
  belongs_to :user

  after_save :log_event

  private
  
  def log_event
      PropertyEvent.new(:property => self.property,
                        :user => self.user,
                        :event_type => "membership",
                        :text => self.user.username + " joined the property").save
  end

end

app/models/property.rb
class Property < ActiveRecord::Base
  belongs_to :user

  has_many :property_events, :dependent => :destroy
  has_many :tickets, :dependent => :destroy
  has_many :memberships, :dependent => :destroy

   # Requires paperclip gem for avatars
   has_attached_file :avatar, :styles => { :medium => "300x300#", :thumb => "100x100#", :large => "500x500#" }, :default_url => ":style/missing_house.jpg"
   validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  after_save :log_event

   private

   def log_event
      PropertyEvent.new(:property => self,
                        :user => self.user,
                        :event_type => "property",
                        :text => "created property " + self.street_address).save
   end

end

app/models/property_event.rb
class PropertyEvent < ActiveRecord::Base
  belongs_to :property
  belongs_to :user
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :property
  belongs_to :user

  after_save :log_event

   # Requires paperclip gem for avatars
   has_attached_file :photo1, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
   validates_attachment_content_type :photo1, :content_type => /\Aimage\/.*\Z/

   has_attached_file :photo2, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
   validates_attachment_content_type :photo2, :content_type => /\Aimage\/.*\Z/


   def log_event
      PropertyEvent.new(:property => self.property,
                        :user => self.user,
                        :event_type => "ticket",
                        :text => "opened ticket " + self.title).save
   end

end

app/models/user.rb
class User < ActiveRecord::Base
   attr_accessor :password
   before_save :encrypt_password
   after_initialize :init

   validates_confirmation_of :password
   validates_presence_of :password, :on => :create
   validates_presence_of :email
   validates_uniqueness_of :email

   has_many :properties
   has_many :property_events
   has_many :tickets
   has_many :memberships, :dependent => :destroy

   # Requires paperclip gem for avatars
   has_attached_file :avatar, :styles => { :medium => "300x300#", :thumb => "100x100#", :large => "500x500#" }, :default_url => "/images/:style/missing.png"
   validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

   def init
      self.role ||= 1
   end

   def self.authenticate(email, password)
      user = find_by_email(email)

      if user && BCrypt::Password.new(user.password_hash) == password
         user
      else
         nil
      end
   end

   def encrypt_password
      if password.present?
         self.password_hash = BCrypt::Password.create(password)
      end
   end

   def is_admin
      return self.role == 2
   end

   def make_admin
      self.role = 2
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :require_login

   helper_method :current_user
   helper_method :require_admin
   helper_method :require_login

   def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
   rescue ActiveRecord::RecordNotFound
      flash[:alert] = "You have been logged out."
      @current_user = nil
      session[:user_id] = nil
   end

   def require_admin
      if !current_user.is_admin
         redirect_to login_url, :notice => "Admin Status Required"
      end
   end

   def require_login
      if !current_user
         redirect_to login_url, :notice => "Login Required"
      end
   end

end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController

   def index
      @property = Property.find(params[:property_id])
      @members = @property.memberships
   end

end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController

   def index
      @memberships = current_user.memberships
   end

   def show
      @property = Property.find(params[:id])
   end

end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
   skip_before_action :require_login

   def index
   end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

   skip_before_action :require_login, only: [:create, :new]

   # The login form
   def new
      @user = User.new
   end

   def create
      user = User.authenticate(params[:email], params[:password])
      if user
         session[:user_id] = user.id
         user.update(:api_token => SecureRandom.hex) unless user.api_token
         # redirect_to root_url
         redirect_to properties_url
      else
         render "new"
      end
   end

   def destroy
   end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController

   def index
      @property = Property.find(params[:property_id])
      @tickets = @property.tickets
   end

   def new
      @property = Property.find(params[:property_id])
      @ticket = Ticket.new
   end

   def create
   end

   def show
      @property = Property.find(params[:property_id])
      @ticket = Ticket.find(params[:id])
   end

end

app/controllers/timeline_controller.rb
class TimelineController < ApplicationController

   def index
   end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   helper_method :can_edit
   skip_before_action :require_login, only: [:create, :new]

   def new
      @user = User.new
   end
   def create
      @user = User.new(user_params)
      if @user.save
         session[:user_id] = @user.id
         redirect_to root_path
      else
         render "new"
      end
   end

   def index
      require_admin
     @users = User.page(params[:page]).order("created_at DESC").all
   end

   def show
      @user = User.find(params[:id])
   end

   def edit
      self_edit_only
      @user = User.find(params[:id])
   end

   # update a user object
   def update
      self_edit_only
      @user = User.find(params[:id])
      if @user.update(update_params)
         redirect_to user_url, :notice => "Update successful!"
      else
         render "edit"
      end
   end

   # Delete a user
   def destroy
      self_edit_only
      @user = User.find(params[:id])
      if @user.destroy
         redirect_to root_path, :notice => "Account deleted!"
      else
         render "edit", :notice => "Deletion failure!"
      end
   end

   private

   def can_edit
      return current_user && (current_user.id == Integer(params[:id]) || current_user.is_admin)
   end

   # Only the same user and admins can edit a user's profile
   def self_edit_only
      #if current_user.id != Integer(params[:id]) && !current_user.is_admin
      if !can_edit
         redirect_to user_url, :notice => "You don't have permission to do that."
      else
      end
   end

   def user_params
      params.require(:user).permit(:email, :username, :password, :password_confirmation)
   end

   def update_params
      params.require(:user).permit(:email, :username, :avatar, :bio, :first_name, :last_name)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/timeline_helper.rb
module TimelineHelper
end

app/views/chats/_chatbox.html.erb
<section class="chatbox">
   <div class="top-bar centered">
      <h5>Group Chat</h5>
   </div>
   <ul class="conversation">
      <li class="other">
         <div class="message">
            <p>Hey! Have you sent that check yet?</p>
         </div>
      </li>
      <li class="self">
         <div class="message">
            <p>Yeah, Robin sent it on the 1st.</p>
         </div>
      </li>
   </ul>

</section>

app/views/memberships/_user_bubble.html.erb
<div class="col-md-2 centered">
   <%= link_to(user_path(member.user)) do %>
      <%= image_tag member.user.avatar.url(:thumb),
         :class => "img-header img-responsive img-circle img-bubble",
         :alt => (member.user.first_name + " " + member.user.last_name) %>
      <br>
      <span><%= member.user.first_name %> <%= member.user.last_name %></span>
      <br>
      <span><strong><%= member.role %></strong></span>
   <% end %>
</div>

app/views/memberships/index.html.erb
<%= render 'properties/property_header', :property => @property %>
<div class="container">
   <div class="row">
      <%= render :partial => 'user_bubble', :collection => @members, :as => :member %>
   </div>
</div>

app/views/properties/_property_event.html.erb
<div class="cd-timeline-block">
   <div class="cd-timeline-img cd-location">
      <%= image_tag "timeline/cd-icon-location.svg" %>
   </div>
   <div class="cd-timeline-content">
      <h2><%= link_to event.user.first_name, user_path(event.user) %></h2>
      <h4><%= event.text %></h4>
      <span class="cd-date"><%= event.created_at %></span>
   </div>
</div>

app/views/properties/_property_header.html.erb
<div class="container down">
   <div class="row centered">
      <div class="col-md-1 half-down">
      </div>
      <div class="col-md-1 half-down">
         <%= link_to(property_path(property)) do %>
            <div class="cd-timeline-img cd-location">
               <%= image_tag "timeline/icon_calendar.svg" %>
            </div>
         <% end %>
      </div>
      <div class="col-md-1 half-down">
         <%= link_to(property_tickets_path(property)) do %>
            <div class="cd-timeline-img cd-location">
               <%= image_tag "timeline/icon_ticket.svg" %>
            </div>
         <% end %>
      </div>
      <div class="col-md-1 half-down">
         <%= link_to(property_memberships_path(property)) do %>
            <div class="cd-timeline-img cd-location">
               <%= image_tag "timeline/icon_user.svg" %>
            </div>
         <% end %>
      </div>
      <div class="col-md-4 cd-timeline-element">
         <%= image_tag property.avatar.url, 
            :class => "img-header img-responsive img-circle", 
            :alt => property.street_address %>
         <span><%= property.street_address %></span>
      </div>
      <div class="col-md-1 half-down">
         <div class="cd-timeline-img cd-location">
            <%= image_tag "timeline/icon_chat.svg" %>
         </div>
      </div>
      <div class="col-md-1 half-down">
         <div class="cd-timeline-img cd-location">
            <%= image_tag "timeline/icon_plus.svg" %>
         </div>
      </div>
      <div class="col-md-1 half-down">
         <div class="cd-timeline-img cd-location">
            <%= image_tag "timeline/icon_exclamation.svg" %>
         </div>
      </div>
      <div class="col-md-1 half-down">
      </div>
   </div>
</div>

app/views/properties/_property_new_button.html.erb
<div class="col-md-4">
   <div class="bubble">
      <div class="shim"></div>
      <%= image_tag "properties/plus_icon.svg", :class => "img-square plus" %>
      <div class="shim"></div>
      <span>Add property...</span>
   </div>
</div>

app/views/properties/_property_preview.html.erb
<div class="col-md-4">
   <%= link_to(property_path(membership.property)) do %>
      <div class="bubble">
         <%= image_tag membership.property.avatar.url, :class => "img-square", :alt => membership.property.street_address %>
         <span><%= membership.property.street_address %></span>
      </div>
   <% end %>
</div>

app/views/properties/index.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<div class="container">
   <div class="row">
      <%= render :partial => 'property_preview', :collection => @memberships, :as => :membership %>
      <%= render 'property_new_button' %>
   </div>
</div>

app/views/properties/show.html.erb
<%= render 'property_header', :property => @property %>
<div class="container">
   <% if @property.property_events.size > 0 %>
      <section id="cd-timeline" class="cd-container">
         <%= render :partial => 'property_event', 
            :collection => @property.property_events,
            :as => :event %>
      </section> 
   <% else %>
      <h1> No events to show </h1>
   <% end %>
</div>

app/views/sales/_block.html.erb
<div class="color-block blue">
   <div class="container">
      <div class="row centered">
         <h1><span class="brand">Leasy</span></h1>
      </div>
   </div>
</div>
<div class="color-block green">
   <div class="container">
      <div class="row centered">
         <h1><span class="brand">Leasy</span></h1>
      </div>
   </div>
</div>
<div class="color-block purple">
   <div class="container">
      <div class="row centered">
         <h1><span class="brand">Leasy</span></h1>
      </div>
   </div>
</div>
<div class="color-block orange">
   <div class="container">
      <div class="row centered">
         <h1><span class="brand">Leasy</span></h1>
      </div>
   </div>
</div>
<div class="color-block red">
   <div class="container">
      <div class="row centered">
         <h1><span class="brand">Leasy</span></h1>
      </div>
   </div>
</div>

app/views/sales/_features.html.erb
<div class="frosted">
   <div class="container">
      <div class="row centered">
         <div class="col-md-6">
            <h1>For tenants:</h1>
            <h2>
               <span class="brand">Leasy</span> gets you heard when communicating with your landlord.
            </h2>
         </div>
         <div class="col-md-6">
            <h1>For landlords:</h1>
            <h2>
               <span class="brand">Leasy</span> makes it painless to keep tabs on your tenants and properties.
            </h2>
         </div>
      </div>
      <br>
      <!--
      <div class="row">
         <div class="col-md-6">
            <img class="img-responsive img-rounded" src="/assets/laptop.jpg">
         </div>
         <div class="col-md-6">
            <img class="img-responsive img-rounded" src="/assets/laptop.jpg">
         </div>
      </div>
      <br>
      -->
   </div>
</div>

app/views/sales/_jumbotron.html.erb
<div class="color-block">
   <div class="container">
      <div class="row centered">
         <h1>Talking to your landlord just got easy.</h1>   
      </div>
   </div>
</div>

app/views/sales/_signup.html.erb
<div class="color-block blue">
   <div class="container">
      <div class="row centered">
         <div class="col-md-2"></div>
         <div class="col-md-8 centered">
            <h3>Get product updates</h3>
            <form class="form-inline">
               <div class="form-group">
                  <input id="emailsignup" class="form-control" type="text" name="email" placeholder="email address">
               </div>
               <button class="btn btn-primary">Let me know!</button>
            </form>
            <p>Sign up for our infrequent mailer to recieve updates on <span class="brand">Leasy</span></p>
         </div>
         <div class="col-md-2"></div>
      </div>
   </div>
</div>

app/views/sales/index.html.erb
<%= render 'sales/jumbotron' %>
<%= render 'sales/block' %>
<%= render 'sales/features' %>
<%= render 'sales/signup' %>

app/views/tickets/_new_ticket.html.erb
<div class="container">

   <div class="cd-form-wrapper cd-container">
      <div class="cd-form">
         <label class="cd-label" for="cd-title">Short title:</label>
         <input type="text" id="cd-title" class="cd-email" name="cd-title" placeholder="garbage disposal jammed">
      </div>
      <br>
      <div class="cd-form">
         <label class="cd-label" for="cd-where">Where is the issue?</label>
         <input type="text" id="cd-where" class="cd-email" name="cd-where" placeholder="kitchen">
      </div>
      <br>
      <div class="cd-form">
         <label class="cd-label" for="cd-desc">Complete problem description:</label>
         <textarea class="cd-email" name="cd-desc" id="cd-desc"
            placeholder="When the garbage disposal is turned on, it makes a grinding sound but does not drain."></textarea>
      </div>
      <br>
      <div class="cd-form">
         <label class="cd-label" for="cd-desc">So far I have tried</label>
         <textarea class="cd-email" name="cd-desc" id="cd-desc"
            placeholder="Using a drain cleaner like drano."></textarea>
      </div>
      <br>
      <div class="cd-form">
         <input type="submit" class="cd-submit" value="Submit" id="submitButton">
      </div>
   </div>


</div>

app/views/tickets/_ticket_header.html.erb
<div class="row spaced-block vertical-center">
   <div class="col-md-1 centered">
      <%= image_tag ticket.user.avatar.url(:thumb),
         :class => "img-header img-responsive img-circle inline",
         :alt => ticket.user.first_name %>
   </div>
   <div class="col-md-9">
      <h2><%= ticket.title %></h2>
      <p>by <%= link_to (ticket.user.first_name + " " + ticket.user.last_name), user_path(ticket.user) %></p>
   </div>
   <div class="col-md-2">
      <button class="btn btn-primary btn-fancy">Close Ticket</button>
   </div>
</div>
<div class="row spaced-block">
   <div class="ticket-description">
      <h3>Description:</h3>
      <p><%= ticket.description %></p>
   </div>
   <div class="ticket-location">
      <h3>Location:</h3>
      <p><%= ticket.location %></p>
   </div>
   <div class="ticket-attempted">
      <h3>Attempted:</h3>
      <p><%= ticket.attempted %></p>
   </div>
   <div class="ticket-photographs">

   </div>
</div>

app/views/tickets/_ticket_preview.html.erb
<div class="row spaced-block vertical-center">
   <div class="col-md-1 centered">
      <%= image_tag ticket.user.avatar.url(:thumb),
         :class => "img-header img-responsive img-circle inline",
         :alt => ticket.user.first_name %>
   </div>
   <div class="col-md-11">
      <h2><%= link_to ticket.title, property_ticket_path(ticket.property, ticket) %></h2>
      <p>by <%= link_to (ticket.user.first_name + " " + ticket.user.last_name), user_path(ticket.user) %></p>
   </div>
</div>

app/views/tickets/index.html.erb
<%= render 'properties/property_header', :property => @property %>
<div class="container">
   <div class="row">
      <div class="col-md-12 centered">
         <h1>Tickets</h2>
      </div>
   </div>
   <%= render :partial => 'ticket_preview', :collection => @tickets, :as => :ticket %>
</div>

app/views/tickets/new.html.erb
<%= render 'properties/property_header', :property => @property %>
<%= render 'new_ticket' %>

app/views/tickets/show.html.erb
<%= render 'properties/property_header', :property => @property %>
<div class="container">
   <% # First, render the ticket header %>
   <%= render 'ticket_header', :ticket => @ticket %>

   <% # Then, render all the responses and comments %>
</div>

app/views/timeline/_header.html.erb
<div class="container down">
   <div class="row centered">
      <div class="col-md-1 half-down">
      </div>
      <div class="col-md-1 half-down">
         <div class="cd-timeline-img cd-location">
            <img src="/assets/timeline/icon_plus.svg">
         </div>
      </div>
      <div class="col-md-1 half-down">
         <div class="cd-timeline-img cd-location">
            <img src="/assets/timeline/icon_user.svg">
         </div>
      </div>
      <div class="col-md-1 half-down">
         <div class="cd-timeline-img cd-location">
            <img src="/assets/timeline/icon_calendar.svg">
         </div>
      </div>
      <div class="col-md-4 cd-timeline-element">
         <img class="img-header img-responsive img-circle" src="/assets/properties/house1.jpg">   
         <span>1525 Nipomo St.</span>
      </div>
      <div class="col-md-1 half-down">
         <div class="cd-timeline-img cd-location">
            <img src="/assets/timeline/icon_chat.svg">
         </div>
      </div>
      <div class="col-md-1 half-down">
         <div class="cd-timeline-img cd-location">
            <img src="/assets/timeline/icon_ticket.svg">
         </div>
      </div>
      <div class="col-md-1 half-down">
         <div class="cd-timeline-img cd-location">
            <img src="/assets/timeline/icon_exclamation.svg">
         </div>
      </div>
      <div class="col-md-1 half-down">
      </div>
   </div>
</div>

app/views/timeline/index.html.erb
<%= render 'header' %>
<% render 'chats/chatbox' %>

<div class="container">
   <section id="cd-timeline" class="cd-container">
      <div class="cd-timeline-block">
         <div class="cd-timeline-img cd-location"><img src="/assets/timeline/cd-icon-location.svg" alt=""></div>
         <div class="cd-timeline-content">
            <h2>Robin mailed his rent check.</h2>
            <span class="cd-date">November 1</span>
         </div>
      </div>
   </section> 
</div>

app/views/users/_edit_form.html.erb
<%= form_for @user, :html => { :multipart => true } do |f| %>
   <% if @user.errors.any? %>
      <div class="errors">
         <ul>
            <% for message in @user.errors.full_messages %>
               <li><%= message %></li>
            <% end %>
         </ul>
      </div>
   <% end %>

   <p>
   <%= f.text_field :email, :placeholder => "Email address" %>
   </p>
   <p>
   <%= f.text_field :username, :placeholder => "Username" %>
   </p>
   <p>
   <%= f.text_field :first_name, :placeholder => "First name" %>
   <%= f.text_field :last_name, :placeholder => "Last name" %>
   <p>
    <%= f.label :bio %>
    <%= f.text_area :bio %>
   </p>
   <p>
    <%= f.label :avatar %>
    <%= f.file_field :avatar %><br>
    <span><%= image_tag @user.avatar.url(:thumb) %></span>
   </p>
   <%= f.submit "Save", :class => "btn btn-success" %>
<% end %>

app/views/users/_new_form.html.erb
<%= form_for @user, :html => { :multipart => true } do |f| %>
   <% if @user.errors.any? %>
      <div class="errors">
         <ul>
            <% for message in @user.errors.full_messages %>
               <li><%= message %></li>
            <% end %>
         </ul>
      </div>
   <% end %>

   <p>
      <%= f.text_field :email, :placeholder => "email address" %>
   </p>
   <p>
      <%= f.password_field :password, :placeholder => "password" %>
   </p>
   <p>
      <%= f.password_field :password_confirmation, :placeholder => "confirm password" %>
   </p>
   <%= f.submit "Save", :class => "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<div id="user-<%= user.username %>" class="row">
   <div class="col-md-6">
      <%= link_to (image_tag user.avatar, :width => "100%"), user_path(user) %>
   </div>
   <div class="col-md-6">
      <div class="page-header">
         <h4> <%= user.first_name %> <%= user.last_name %> <small><%= link_to user.username, user_path(user) %></small></h4>
      </div>
      <p><%= user.bio %></p>
   </div>
</div>

app/views/users/_user_header.html.erb
<div id="user-header-carousel" class="carousel slide" data-ride="carousel">
   <div class="carousel-inner">
      <div class="item active" style="max-height: 400px; overflow: hidden;">
         <%= image_tag user.avatar.url, :width => "100%", :class => "img img-rounded"  %>
         <div class="carousel-caption">
            <%= image_tag user.avatar.url(:thumb), :class => "img img-rounded" %>
            <h1><%= user.username %></h1>
            <p><%= user.bio %>
            <%= link_to content_tag(:span, "", class:"glyphicon glyphicon-pencil"), edit_user_path(user) if can_edit %>
            </p>
         </div>
      </div>
   </div>
</div>

app/views/users/edit.html.erb
<div class="container">
   <%= render 'user_header', :user => @user %>
   <br>
   <div class="panel panel-default">
      <div class="panel-heading">
         <h3 class="panel-title">Edit User Profile</h3>
      </div>
      <div class="panel-body">
         <%= render 'edit_form' %>
      </div>
   </div>
   <div class="panel panel-default">
      <div class="panel-heading">
         <h4 class="panel-title">
            Dangerous Actions
         </h4>
      </div>
      <div class="panel-body">
         <%= link_to 'Delete', user_path(@user), method: :delete, data: {confirm: 'Are you sure? This will delete all data associated with this account and cannot be undone.'}, :class => "btn btn-danger"  %>
      </div>
   </div>
</div>

app/views/users/index.html.erb
<div class="container">
   <%= render(@users) %>
   <%= will_paginate @users %>
</div>

app/views/users/new.html.erb
<div class="container">

   <h1>Sign up</h1>

   <%= render 'new_form' %>

</div>

app/views/users/show.html.erb
<div class="container">
   <%= render 'user_header', :user => @user %>
</div>